version: "3.7"
services:
    postgres_ecommerce_user:
        image: postgres:latest
        ports:
            - ${DB_PORT}:${DB_PORT}
        env_file:
            - ./.env.ecommerce_user
        networks:
            net_postgres:
                ipv4_address: 172.16.18.4
    ecommerce_user:
        image: vinny1892/ecommerce_user
        depends_on:
            - postgres_ecommerce_user
        env_file:
            - ./.env.ecommerce_user
        ports:
            - ${GRPC_PORT}:${GRPC_PORT}
        networks:
            net_postgres:
                ipv4_address: 172.16.18.3
    ecommerce_api_gateway:
        image: vinny1892/ecommerce_api_gateway
        env_file:
            - ./.env.ecommerce_api_gateway
        ports:
            - ${PORT}:${PORT}
        networks:
            net_postgres:
                ipv4_address: 172.16.18.2
    # ecommerce_cart:
    #     env_file:
    #         - ./.env
    #     ports:
    #         - ${GRPC_PORT_ECOMMERCE_CART}:${GRPC_PORT_ECOMMERCE_CART}
    #     networks:
    #         net_postgres:
    #             ipv4_address: 172.16.18.5
    # ecommerce_product:
    #     image:
    #     env_file:
    #         - ./.env
    #     ports:
    #         ${GRPC_PORT_ECOMMERCE_PURCHASE}:${GRPC_PORT_ECOMMERCE_PURCHASE}
        

networks:
    net_postgres:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.18.0/24                                                                                                                               
